- name: printing
  hosts: web
  become: yes
  tasks: 
  - name: printing
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

  - name: printing
    ansible.builtin.debug:
      msg: "{{user}}"
  
  - name: printing
    ansible.builtin.command: useradd expense

    when: user.rc!=0
    
    

