- name: printing
  hosts: web
  tasks: 
  - name: printing
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

  - name: printing
    ansible.builtin.debug:
      msg: "{{user}}"

